### PR TITLE
fix walkthrough video link

### PR DESCRIPTION
**Pull request by PalashBansal**
fixes issue https://github.com/AutoMapper/AutoMapper/issues/3484

### CODE REVIEW

**Review by lbargaoanu — APPROVED** [review]
Thanks!

**Comment by lbargaoanu** [comment]
@jbogard Perhaps remove the link altogether? Seems too old to be of much use now.

**Comment by PalashBansal** [comment]
> @jbogard Perhaps remove the link altogether? Seems too old to be of much use now.

I guess better than nothing, as it's helping me understand automapper. May be can replace once new video tutorial is available.

**Comment by jbogard** [comment]
Yeah I'd rather remove the link. Not much of it is accurate. You're better off with the docs and maybe Pluralsight?

**Pull request merged**
