### PR TITLE
Add Links to other Automapper GH Repositories

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Not very well versed with websites.  Made something simple to explain things.

Open to review

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
when do you think you might update the site?

**Comment by jbogard** [comment]
......I thought it auto updated on merge

**Comment by TylerCarlson1** [comment]
I don't see update in http://automapper.org/  maybe it goes somewhere else?

**Comment by jbogard** [comment]
Ahhhh I forgot I moved to GH pages. You'll need to branch off of the gh-pages branch for your PR.

And naturally it's totally different.

**Pull request merged**
